In [18]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [19]:
df = pd.read_csv("ecommerce_sales_analysis.csv", encoding="latin1")

In [20]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [21]:
df.info(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [23]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [38]:
df.sort_values("revenue", ascending=False).head(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
809,10810,3/20/2024,1890,Electronics,South,7,594.42,0.01,Card,4,4.9,4119.33
4883,14884,5/16/2035,1146,Electronics,South,7,583.31,0.00,Card,5,4.4,4083.17
2214,12215,1/24/2028,1113,Electronics,South,7,591.15,0.02,Wallet,1,3.2,4055.29
3101,13102,6/29/2030,1699,Beauty,East,7,596.12,0.04,COD,6,3.0,4005.93
3686,13687,2/4/2032,1831,Clothing,North,7,578.59,0.03,COD,8,1.6,3928.63
157,10158,6/7/2022,1779,Electronics,North,7,571.07,0.02,COD,10,4.5,3917.54
3349,13350,3/4/2031,1082,Electronics,West,7,574.15,0.03,Card,10,2.7,3898.48
321,10322,11/18/2022,1608,Electronics,West,7,585.43,0.05,Card,10,3.2,3893.11
661,10662,10/24/2023,1550,Clothing,East,7,581.67,0.05,COD,3,1.2,3868.11
4305,14306,10/15/2033,1283,Beauty,South,7,555.09,0.02,COD,11,4.9,3807.92

In [39]:
df.sort_values("unit_price", ascending= True)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
3643,13644,12/23/2031,1435,Clothing,South,1,15.15,0.26,Card,5,3.5,11.21
2797,12798,8/29/2029,1637,Clothing,West,4,15.18,0.03,Card,3,2.8,58.90
3084,13085,6/12/2030,1920,Clothing,North,7,15.19,0.17,Card,6,3.1,88.25
2353,12354,6/11/2028,1481,Clothing,North,5,15.32,0.14,Card,5,1.3,65.88
4271,14272,9/11/2033,1442,Beauty,South,7,15.50,0.32,COD,10,3.7,73.78
...,...,...,...,...,...,...,...,...,...,...,...,...
135,10136,5/16/2022,1520,Home,South,3,599.32,0.29,COD,10,2.7,1276.55
3755,13756,4/13/2032,1515,Electronics,West,7,599.50,0.23,Wallet,4,1.9,3231.30
2228,12229,2/7/2028,1972,Home,East,4,599.68,0.21,Card,2,4.1,1894.99
2053,12054,8/16/2027,1607,Electronics,East,5,599.89,0.11,Card,4,4.9,2669.51
2701,12702,5/25/2029,1951,Electronics,West,3,599.96,0.15,COD,1,1.2,1529.90

In [41]:
df.sort_values("delivery_days", ascending= True)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
2004,12005,6/28/2027,1401,Home,South,5,545.76,0.12,COD,1,3.6,2401.34
4378,14379,12/27/2033,1200,Electronics,West,3,371.37,0.06,COD,1,3.8,1047.26
4380,14381,12/29/2033,1904,Electronics,North,4,493.29,0.25,COD,1,1.3,1479.87
3509,13510,8/11/2031,1147,Clothing,East,3,172.62,0.10,Card,1,1.5,466.07
398,10399,2/3/2023,1111,Clothing,North,4,75.43,0.28,Wallet,1,3.3,217.24
...,...,...,...,...,...,...,...,...,...,...,...,...
3916,13917,9/21/2032,1695,Clothing,West,7,505.52,0.35,COD,11,3.1,2300.12
3914,13915,9/19/2032,1812,Electronics,West,6,31.96,0.11,Wallet,11,3.6,170.67
3913,13914,9/18/2032,1840,Clothing,North,3,360.97,0.11,Wallet,11,5.0,963.79
3923,13924,9/28/2032,1532,Clothing,South,4,545.17,0.15,Card,11,4.9,1853.58
3823,13824,6/20/2032,1558,Home,East,7,317.36,0.01,COD,11,2.3,2199.30

In [43]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [44]:
df.size

60000

In [45]:
df.shape

(5000, 12)

In [46]:
df.sort_values("quantity", ascending= True)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
816,10817,3/27/2024,1038,Beauty,North,1,476.61,0.32,COD,4,3.5,324.09
2600,12601,2/13/2029,1642,Home,East,1,233.98,0.32,COD,7,4.1,159.11
1240,11241,5/25/2025,1738,Electronics,South,1,370.00,0.07,Card,7,1.8,344.10
4480,14481,4/8/2034,1703,Clothing,East,1,388.60,0.00,Wallet,1,2.6,388.60
3332,13333,2/15/2031,1466,Clothing,East,1,41.86,0.06,Card,6,2.6,39.35
...,...,...,...,...,...,...,...,...,...,...,...,...
2874,12875,11/14/2029,1018,Beauty,North,7,283.25,0.27,COD,2,4.4,1447.41
2867,12868,11/7/2029,1323,Electronics,North,7,392.87,0.24,Card,6,2.9,2090.07
2866,12867,11/6/2029,1970,Home,North,7,244.31,0.26,Wallet,1,1.9,1265.53
2935,12936,1/14/2030,1739,Electronics,South,7,107.40,0.01,COD,7,1.6,744.28
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90