In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv("ecommerce_sales_analysis.csv", encoding="latin1")

In [4]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [6]:
clean_df = df[["customer_id", "product_category","region", "quantity", "unit_price", "discount", "delivery_days", "customer_rating", "revenue" ]]

In [7]:
clean_df

,customer_id,product_category,region,quantity,unit_price,discount,delivery_days,customer_rating,revenue
0,1102,Beauty,South,7,373.65,0.28,10,4.7,1883.20
1,1435,Clothing,South,7,47.74,0.09,6,3.9,304.10
2,1860,Beauty,East,3,311.28,0.31,6,2.5,644.35
3,1270,Electronics,West,5,524.47,0.02,6,1.6,2569.90
4,1106,Clothing,West,5,139.87,0.33,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...
4995,1289,Clothing,West,2,371.74,0.27,3,2.3,542.74
4996,1294,Beauty,North,3,553.67,0.14,11,2.2,1428.47
4997,1450,Beauty,West,3,77.22,0.24,6,3.4,176.06
4998,1903,Electronics,South,4,138.41,0.21,4,2.8,437.38
4999,1214,Home,East,7,231.58,0.34,5,3.9,1069.90

In [24]:
clean_df.describe()

,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

# Calculate the main KPIs
 • Total revenue
 • Total orders
 • Total customers
 • Total quantity sold
 • Average order value
 • Average customer rating
 • Average delivery time

In [35]:
clean_df.describe().loc['mean',['revenue', "unit_price", "discount", "delivery_days" ]]

revenue          1021.955148
unit_price        308.418774
discount            0.179984
delivery_days       6.118800
Name: mean, dtype: float64